// src/components/ChartPolyline/ChartPolyline.tsx
import React, { Component } from 'react';
import { connect } from 'react-redux';

import { ChartMetaData, SortedY } from '~/models/dataModel';
import { CombinedState } from '~/store/reducers';
import { FrameState } from '~/store/reducers/chartFrame/frameReducer';
import { ChartSvg } from '~/hocComponents/ChartMain/ChartMain';
import { Settings } from '~/store/reducers/rootReducers/rootReducers';


interface ChartPolylineOwnProps {
	svg: ChartSvg;
	isThumb?: boolean;
}

interface ChartPolylineStateProps {
	frameState: FrameState;
	settings: Settings;
}

interface ChartPolylineDispatchProps {
}

type ChartPolylineCombinedProps = ChartPolylineOwnProps & ChartPolylineStateProps & ChartPolylineDispatchProps;


class ChartPolyline extends Component<ChartPolylineCombinedProps> {
	
	private buildPolyline(svg: ChartSvg): JSX.Element[] {
		const polylineArr: JSX.Element[] = [];
		const yDataLen: number = this.props.frameState.visibleData.length;
		for (let yDataIdx = 0; yDataIdx < yDataLen; yDataIdx++) {
			const curData: SortedY = this.props.frameState.visibleData[yDataIdx];
			

			let pointsArr: string[] = [];
			if (this.props.isThumb) {
				pointsArr = this.calcXY(curData.data, svg);
			} else {
				const curDataArr: ChartMetaData = curData.data.slice(this.props.frameState.from, this.props.frameState.to);
				pointsArr = this.calcXY(curDataArr, svg);
			}
			
			
			polylineArr.push((
				<polyline
					key={curData.columnKey}
					points={pointsArr.join()}
					stroke={curData.color}
					strokeWidth={svg.polylineStrokeWidth}
					visibility={curData.isVisible ? 'visible' : 'hidden'}
					fill="none"/>
			))
		}
		
		return polylineArr;
	}
	
	private calcXY(data: ChartMetaData, svg: ChartSvg): string[] {
		const pointsArr = [];
		const dataLength = data.length;
		const paddingBot = svg.paddingBot ? svg.paddingBot : 0;
		
		for (let dataIndex = 0; dataIndex < dataLength; dataIndex++) {
			const curItem = Number(data[dataIndex]);
			const pointStepGap: number = svg.width / (dataLength - 1);
			const xPoint = (pointStepGap * dataIndex).toFixed(4);
			// get proportional val of Y point
			let yPoint = curItem / this.props.frameState.maxValHeight;
			yPoint *= svg.height - paddingBot;
			// turn over lines and add ver padding
			yPoint = Number((svg.height - yPoint - paddingBot).toFixed(4));
			
			// create lines array [x,y]
			pointsArr.push(`${xPoint} ${yPoint}`);
		}
		
		return pointsArr;
	}
	
	render() {
		const polylineArr = this.buildPolyline(this.props.svg);
		
		return (<g>{polylineArr}</g>)
	};
}

const mapStateToProps = (state: CombinedState): ChartPolylineStateProps => {
	return {
		frameState: state.frameState,
		settings: state.rootState.settings
	}
};

export default connect(mapStateToProps)(ChartPolyline);

// src/app/chart/chart-elements/chart-polyline/chart-polyline.component.ts
import { Component, Input, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';

import { ChartSvg } from '../../chart.component';
import { ChartEventsService, TogglePolylineObj, VisibleFrameObj } from '../../chart-services/chart-events.service';
import { ChartMetaData, SortedY } from '../../../app.component';
import { Subscription } from 'rxjs';

interface PolylineObj {
  points: string[];
  stroke: string;
  dataName: string;
  dataType: string;
  strokeWidth: number;
  visibility: string;
  fill: string;
}

@Component({
  selector: '[app-chart-polyline]',
  templateUrl: './chart-polyline.component.html',
  styleUrls: ['./chart-polyline.component.scss']
})
export class ChartPolylineComponent implements OnInit, OnDestroy {
  @Input() visibleFrame: VisibleFrameObj;
  @Input() svg: ChartSvg;
  @Input() isThumb: boolean;
  
  polylineArr: PolylineObj[];
  private sub1: Subscription;
  
  
  constructor(private ces: ChartEventsService) {}
  
  
  ngOnInit() {
    this.polylineArr = this.buildPolyline();
  
    if (!this.isThumb) {
      this.sub1 = this.ces.visibleFrameSubject
        .subscribe((visibleFrame: VisibleFrameObj) => {
          if (visibleFrame) {
            this.visibleFrame = visibleFrame;
            this.updatePolyline();
          }
        });
    }
  }
  
  ngOnDestroy() {
    this.sub1.unsubscribe();
  }
  
  
  private buildPolyline(): PolylineObj[] {
    const polylineArr: PolylineObj[] = [];
    const yDataLen = this.visibleFrame.visibleArr.length;
    for (let yDataIdx = 0; yDataIdx < yDataLen; yDataIdx++) {
      const curData: SortedY = this.visibleFrame.visibleArr[yDataIdx];
      const curDataArr: ChartMetaData = curData.data.slice(this.visibleFrame.from, this.visibleFrame.to);
      const pointsArr: string[] = this.calcXY(curDataArr);
  
      polylineArr.push({
        points: pointsArr,
        stroke: curData.color,
        dataName: curData.name,
        dataType: curData.type,
        strokeWidth: this.svg.polylineStrokeWidth,
        visibility: curData.isVisible ? 'visible' : 'hidden',
        fill: 'none'
      });
    }
    
    return polylineArr;
  }
  
  private updatePolyline(): void {
    const yDataLen = this.visibleFrame.visibleArr.length;
    for (let yDataIdx = 0; yDataIdx < yDataLen; yDataIdx++) {
      const curData: SortedY = this.visibleFrame.visibleArr[yDataIdx];
      const curPolyline: PolylineObj = this.polylineArr[yDataIdx];
      const curDataArr: ChartMetaData = curData.data.slice(this.visibleFrame.from, this.visibleFrame.to);
  
      curPolyline.points = this.calcXY(curDataArr);
      curPolyline.visibility = curData.isVisible ? 'visible' : 'hidden';
    }
  }
  
  private calcXY(data: ChartMetaData): string[] {
    const pointsArr = [];
    const dataLength = data.length;
    const paddingBot = this.svg.paddingBot ? this.svg.paddingBot : 0;
    
    for (let dataIndex = 0; dataIndex < dataLength; dataIndex++) {
      const curItem = Number(data[dataIndex]);
      const pointStepGap: number = this.ces.width / (dataLength - 1);
      const xPoint = (pointStepGap * dataIndex).toFixed(4);
      // get proportional val of Y point
      let yPoint = curItem / this.visibleFrame.maxValHeight;
      yPoint *= this.svg.height - paddingBot;
      // turn over lines and add ver padding
      yPoint = Number((this.svg.height - yPoint - paddingBot).toFixed(4));

      // create lines array [x,y]
      pointsArr.push(`${xPoint} ${yPoint}`);
    }
    
    return pointsArr;
  }
}

<svg:polyline
  *ngFor="let polyline of polylineArr"
  [attr.points]="polyline.points"
  [attr.stroke]="polyline.stroke"
  [attr.data-name]="polyline.dataName"
  [attr.data-type]="polyline.dataType"
  [attr.stroke-width]="polyline.strokeWidth"
  [attr.visibility]="polyline.visibility"
  [attr.fill]="polyline.fill"
/>
